export const JSPF_VERSION='1.0';
export const XSPF_VERSION='1.0';
export const XSPF_XMLNS="http://xspf.org/ns/0/";
export const REPO_URL = 'https://github.com/spiff-radio/jspf-cli';
export const ISSUES_URL = REPO_URL + '/issues';
export const XSPF_URL='https://www.xiph.org/';
export const JSON_VALIDATOR_URL='https://jsonlint.com';
export const JSPF_SPECS_URL='https://www.xspf.org/spec';
export const DEFAULT_JSON_SCHEMA_VERSION='https://json-schema.org/draft/2020-12/schema';
